# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0072088e82ddd91497c04aa44e584ac512c97f4b4d49d550514fe31ac340c5c18c93097d9856d642182bbc131a9f62d6759406c029fd1bedb576cac01bed0281

test:
  secret_key_base: d72793933df5e54c0e00c4439fb2c99c3b2cb22751db62f80dc1287de6923591567d6a1a0108ee313bf01bb71d54ac037db21a6a8ad53cb696254feb528bb0a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
